export const FILTER_TYPES = {
    SELECTED_YEAR: 'SELECTED_YEAR',
    GENRES_FETCHED: 'GENRES_FETCHED',
    CHEKED: 'CHEKED',
    SELECTED_BY: 'SELECTED_BY',
    RESET: 'RESET'
}

export const PAGINATION_TYPES = {
    FORWARD: 'FORWARD',
    BACK: 'BACK',
    SET_CURRENT_PAGE: 'SET_CURRENT_PAGE'
}

export const AUTH_TYPES = {
    SET_AUTH: 'SET_AUTH',
    SET_USER_ID: 'SET_USER_ID'
}

export const FAVORITE_TYPES = {
    SET_FAV_FETCHED: 'SET_FAV_FETCHED',
    SET_FAV: 'SET_FAV',
    SET_TOGGLE: 'SET_TOGGLE',
    SET_FILMS: 'SET_FILMS'
}
